name: Check Dump File Exists

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  check-dump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if employees.sql exists
        run: |
          if [ -f "employees.sql" ]; then
            echo "✅ employees.sql found"
          else
            echo "❌ employees.sql not found"
            exit 1
          fi
